title: Selva Kumar Rajendran
description: Observing and finding pattern interests me.
In my 9 years of experience in Data Analysis & Reporting, I have gathered knowledge in SQL (MS Dialect) | Qlikview | Qliksense | Power BI | Excel | SSIS (ETL).
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
